name: spring_boot_oauth2

services:
  mysql:
    build: ./mysql/
    container_name: mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}

    ports:
      - "3306:${MYSQL_PORT}"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - default_network

  authentication:
    build: ./authentication/
    container_name: authentication

    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9000/.well-known/openid-configuration"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 8s

    depends_on:
      - mysql

    env_file:
      - .env

    ports:
      - "9000:${AUTHENTICATION_PORT}"

    networks:
      - default_network
  resource:
    build: ./resource/
    container_name: resource

    depends_on:
      - mysql
      - authentication

    env_file:
      - .env

    ports:
      - "8080:${RESOURCE_PORT}"

    networks:
      - default_network
  client:
    build: ./client/
    container_name: client

    depends_on:
      - mysql
      - authentication

    env_file:
      - .env

    ports:
      - "3000:${CLIENT_PORT}"

    networks:
      - default_network
  
volumes:
  mysql_data:
    name: mysql_data

networks:
  default_network:
    driver: bridge