logging:
  level:
    root: "warn"
    org.springframework.web: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.security.oauth2.client: TRACE
    org.springframework.security.oauth2.core.endpoint: TRACE
    org.springframework.security.oauth2.client.endpoint: TRACE
server:
  port: ${CLIENT_PORT}
  servlet:
    session:
      cookie:
        name: CLIENTSESSION
spring:
  application:
    name: "client"
  security:
    oauth2:
      client:
        registration:
          web-client-oidc:
            provider: auth-server
            client-id: web-client
            client-secret: 123456
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile
        provider:
          auth-server:
            issuer-uri: ${AUTHENTICATION_URL}:${AUTHENTICATION_PORT}
            authorization-uri: ${AUTHENTICATION_URL}:${AUTHENTICATION_PORT}/oauth2/authorize
            token-uri: ${AUTHENTICATION_URL}:${AUTHENTICATION_PORT}/oauth2/token
            jwk-set-uri: ${AUTHENTICATION_URL}:${AUTHENTICATION_PORT}/oauth2/jwks
            user-info-uri: ${AUTHENTICATION_URL}:${AUTHENTICATION_PORT}/userinfo
            user-name-attribute: sub